INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_COURSES) VALUES(199,'Billy', 'SCIENCE, MATH, ENGLISH, HISTORY');
INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_COURSES) VALUES(300,'Bob', 'MATH');
INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_COURSES) VALUES(299,'Jen', 'SCIENCE, HISTORY');
INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, STUDENT_COURSES) VALUES(100,'Mark', 'MATH, GYM, ART');