ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_ACCT_OWNER
FOREIGN KEY (ACCT_OWNER_ID) REFERENCES ACCT_OWNER(ACCT_OWNER_ID);
/
ALTER TABLE ADMINISTRATOR
ADD CONSTRAINT FK_ADMINISTRATOR_ACCT_OWNER
FOREIGN KEY (ADMIN_ID) REFERENCES ACCT_OWNER(ADMIN_ID);
/
ALTER TABLE ACCT_OWNER
ADD UNIQUE(ADMIN_ID);
/
ALTER TABLE ACCOUNT DROP COLUMN ADMIN_ID;
/
CREATE SEQUENCE SQ_ACCOUNT_PK
START WITH 1000
INCREMENT BY 1;
/
CREATE SEQUENCE SQ_ACCT_OWNER_PK
START WITH 100
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER TR_INSERT_ACCT_OWNER
BEFORE INSERT ON ACCT_OWNER
FOR EACH ROW
BEGIN
    SELECT SQ_ACCT_OWNER_PK.NEXTVAL INTO :NEW.ACCT_OWNER_ID FROM DUAL;
END;    
/
CREATE OR REPLACE TRIGGER TR_INSERT_ACCOUNT
BEFORE INSERT ON ACCOUNT
FOR EACH ROW
BEGIN
    SELECT SQ_ACCOUNT_PK.NEXTVAL INTO :NEW.ACCT_NMBR FROM DUAL;
END;
/

INSERT INTO ACCOUNT (ACCT_BAL) VALUES (200);
/
INSERT INTO ACCT_OWNER (ACCOUNT_OWNER.FNAME) VALUES ('BOB');
/
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
/
ALTER TABLE ACCOUNT DROP CONSTRAINT FK_ACCOUNT_ACCT_OWNER;   
/
ALTER TABLE ACCOUNT DROP CONSTRAINT FK_ADMINISTRATOR_ACCT_OWNER;
/
ALTER TABLE ADMINISTRATOR DROP CONSTRAINT FK_ADMINISTRATOR_ACCT_OWNER;
/
ALTER TABLE ACCOUNT
ADD FOREIGN KEY (ACCT_OWNER_ID) REFERENCES ACCT_OWNER(ACCT_OWNER_ID);
/
ALTER TABLE ADMINISTRATOR ADD ACCT_OWNER_ID INT;
/
ALTER TABLE ADMINISTRATOR
ADD FOREIGN KEY (ACCT_OWNER_ID) REFERENCES ACCT_OWNER(ACCT_OWNER_ID);

ALTER TABLE ADMINISTRATOR DROP COLUMN ACCT_OWNER_ID;
/
ALTER TABLE ACCT_OWNER ADD ADMIN_ID NUMBER;
/
ALTER TABLE ACCT_OWNER DROP COLUMN ADMIN_ID;

/
DROP TABLE ADMINISTRATOR;
/
INSERT INTO ACCOUNT (ACCT_BAL, ACCT_OWNER_ID) VALUES (0, 120);
/
DELETE FROM ACCOUNT WHERE acct_nmbr = 1023;
/
UPDATE ACCOUNT SET ACCT_BAL = ACCT_BAL +50 WHERE acct_nmbr = 1024;
/
SELECT ACCT_BAL FROM ACCOUNT WHERE ACCT_NMBR = 1022;
/
UPDATE ACCOUNT SET ACCT_BAL = 340 WHERE ACCT_NMBR = 1027;
/