server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: student-gateway
cloud:
    gateway:
      discovery:
        locator: 
          enabled: true
      routes: #every route can have id, uri, predicates, and filters
       - id: student-service
         uri: lb://student-service
         predicates: 
           - Path=/student/**